# Generated by Django 3.0.8 on 2020-07-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
